/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type TunnelDiagnosticStep = {
  /**
   * Elapsed probe time in milliseconds
   */
  durationMs: number;
  /**
   * Bounded failure category, never raw error text
   */
  failure: string;
  /**
   * pass, fail, not_applicable or not_tested
   */
  state: string;
};

/** @internal */
export const TunnelDiagnosticStep$inboundSchema: z.ZodMiniType<
  TunnelDiagnosticStep,
  unknown
> = z.pipe(
  z.object({
    duration_ms: z.int(),
    failure: z.string(),
    state: z.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "duration_ms": "durationMs",
    });
  }),
);

export function tunnelDiagnosticStepFromJSON(
  jsonString: string,
): SafeParseResult<TunnelDiagnosticStep, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TunnelDiagnosticStep$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TunnelDiagnosticStep' from JSON`,
  );
}
